version: '3.8'

services:
  medical-records-app:
    build:
      context: .
      dockerfile: Dockerfile
    container_name: medical-records-app
    restart: always
    ports:
      - "80:3000"  # 容器内3000端口映射到主机的80端口
    environment:
      - NODE_ENV=production
    volumes:
      - medical-records-data:/app/data

volumes:
  medical-records-data:
